== Changing the start up background on a Linux OT

This guide shows your how to change the background image that you see when starting up an OT. 

 .  	Find a desired background image and save this image as the required name for the specific OT, For example an OT1210's file is named ‘1280x800.jpg’.
 
 .OT resolutions
 [NOTE] 
 ====
 OT1207/1207+ = 800x480
 OT1210/OT1210+ = 1280x800
 OT1212 = 1280x800
 OT1215/OT1215+ = 1920x1080
 ====

 . 	Using the FTP in solutioncenter, drag and drop this file from your pc to the OT in the directory called /home/vis.
  
 .	Make a connection with the OT via putty, Login with the following credentials username: vis Password: bachmann.
  
 .	  Type ‘ls’, you should now be in the /home/vis directory (you could recognize this by checking if the lconfig.ini file is there).
  
 .  	If you are in /home/vis, type ‘cd ../..’. To check type ‘ls’, you should now see the usr folder here.
  
 .	  Now type: ‘mv /home/vis/1280x800.jpg /usr/share/bachmann-config’ 
  
 .	Reboot the OT and if the steps are followed the background image should now have changed to your desired image.
